version: 1.0

uown: 67ab2db0-fb5f-4a08-af9e-93530f283a6d
command: "src/build.sh"

docker:
  # base-image: docker-local.artifactory.uber.internal:5922/devexp/udj-go-base:latest
  base-image: docker-local.artifactory.uber.internal:5922/devexp/generic-ci-tm1:latest
  shell: true
  with-host-docker: true

vault_secrets:
  - path: /buildkite/migrated-from-jenkins/jenkins_activedir_password
    alias: TM1_PASSWORD

notify:
  - email: "${BUILDKITE_BUILD_AUTHOR_EMAIL:-epm-eng@uber.com}"
    if: build.state == "passed"

  - email: "${BUILDKITE_BUILD_AUTHOR_EMAIL:-epm-eng@uber.com}"
    if: build.state == "failed"