[global]
disable-pip-version-check = yes
extra-index-url = https://pypi.python.org/simple
index-url = http://artifactory.uber.internal:4587/artifactory/api/pypi/pypi/simple/
trusted-host = artifactory.uber.internal
timeout = 60
